FROM maven:3.6.3-jdk-11-slim AS maven-build
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
RUN mvn -f /usr/src/app/pom.xml clean install

FROM openjdk:13-jdk-alpine
LABEL maintainer="jeee187-GTA@EPISENSCA" build_date="2020-11-21"
COPY --from=maven-build /usr/src/app/target/*.jar /usr/app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]
