version: '3'
services:
  front:
    image: jeee187/episen-sca-gta-front:0.2
    container_name: "front-orders"
    ports:
      - "80:80"
    links:
      - "back:backend-server"
  back:
    image: jeee187/episen-sca-gta-back:0.1
    container_name: "backend-server"
    hostname: backend-server
    ports:
      - "8080:8080"
    volumes:
      - orders-data:/etc
volumes:
  orders-data: