version: '3'
services:
  episen-sca-gta-back:
    build: ./episen-sca-gta-backend
    container_name: "backend"
    ports:
      - "8080:8080"
    links:
      - "episen-sca-gta-front"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.8'
          memory: 384m
        reservations:
          cpus: '0.6'
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 3

    volumes:
      - /srv/gta-backend/data:/home/executor/app/data
      - /srv/gta-backend/log:/home/executor/app/log


  episen-sca-gta-front:
    build: ./episen-sca-gta-front
    container_name: "frontend"
    ports:
      - "80:80"
    volumes:
      - /srv/mem-nginx/log:/var/log/nginx
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.8'
          memory: 384m
        reservations:
          cpus: '0.6'
          memory: 256M
      restart_policy:
        condition: on-failure
        max_attempts: 3