version: '3'
services:
  gta-front:
    image: jeee187/episen-sca-gta-front:1.0
    ports:
      - "80:80"
      - "81:81"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
    links:
      - "back:backend-server"
    volumes:
      - frontlog:/etc
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 200M
        reservations:
          cpus: "0.5"
          memory: 100M
      restart_policy:
        condition: on-failure
    links:
      - "gta-back:backend-server"
  gta-back:
    image: jeee187/episen-sca-gta-back:1.0
    hostname: backend-server
    ports:
      - "8080:8080"
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    volumes:
      - orders-data:/etc
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "1"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
      restart_policy:
        condition: on-failure
volumes:
  orders-data:
  frontlog:
    