version: "3"
services:
  episen-sca-lbe-back:
    image: jeee187/episen-sca-gta-back:1.0
    ports:
      - "8080"
    volumes:
      - ./log

  episen-sca-lbe-front:
    image: jeee187/episen-sca-gta-front:1.0
    ports:
      - "80"
    volumes:
      - ./logfront