version: '3'
services:
  gta-front:
    image: jeee187/episen-sca-gta-front:1.0
    container_name: "front-orders"
    ports:
      - "80:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://front-orders:80"]
    links:
      - "back:backend-server"
    volumes:
      - frontlog:/etc
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.6"
          memory: 256M
        reservations:
          cpus: "0.6"
          memory: 200M
      restart_policy:
        condition: on-failure
    links:
      - "gta-back"

  gta-back:
    image: jeee187/episen-sca-gta-back:1.0
    container_name: backend-server
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend-server:8080"]
    volumes:
      - orders-data:/etc
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.6"
          memory: 300M
        reservations:
          cpus: "0.5"
          memory: 200M
      restart_policy:
        condition: on-failure
volumes:
  orders-data:
  frontlog:
    