version: '3'
services:
  front:
    image: jeee187/episen-sca-gta-front:1.0
    container_name: "front-orders"
    ports:
      - "80:80"
    volumes :
      - front-data:/etc
    links:
      - "back:backend-server"
  back:
    image: jeee187/episen-sca-gta-back:1.0
    container_name: "backend-server"
    hostname: backend-server
    ports:
      - "8080:8080"
    volumes:
      - orders-data:/logs
volumes:
  orders-data:
  front-data: